### ISSUE TITLE
Attempting to reference a deleted function

### ISSUE THREAD

**Issue by NoAvailableAlias** [fr00b0/nod#1] opened 2015-04-30 22:21 UTC
Hi, in your readme you have several locations where you do:
```
connection = signal.connect ...
```
This operator is deleted and only a move constructor remains. This causes errors in VS about deleted functions. Eventually found the actual expected usage of the nod connection objects in your unit tests. I would recommend correcting the readme as this causes some confusion.

**Comment by fr00b0** [comment] 2015-05-01 14:02
I've looked through the example usage and made a few corrections, but not related to the connection management. I've also added the example usage code to the test project to make sure it builds and runs.

Creating connections the way the readme explains should be legal using only move semantics.

What version of Visual Studio are you using?

I have successfully compiled and executed the example usage with
 - Visual Studio 2013 Update 4, compiler version 18.00.31101
 - gcc 4.9.1

**Comment by NoAvailableAlias** [comment] 2015-05-01 14:05
Sorry, forgot that part. VS 2013 update 4. Don't have the specific version available right now.

**Comment by fr00b0** [comment] 2015-05-01 17:08
The latest changes has resolved this issue, at least what I have been able to reproduce.

If you use the updated version of `nod.hpp` you should be able to to change your code into [something like this](https://gist.github.com/fr00b0/bc740af2469fb4ec5195)

Let me know if this fixes your problems, and if it does then I will close this issue.

**Comment by NoAvailableAlias** [comment] 2015-05-01 21:47
Seems to have done the trick. Thanks, everything works. If you would like to know how your implementation compares to a number of others, see this [page](https://github.com/NoAvailableAlias/nano-signal-slot/tree/FT/benchmark#performance). (note that a number of non thread safe implementations are also included).

**Comment by fr00b0** [comment] 2015-05-02 10:14
Very interesting! Even though performance isn't the main focus of the nod library, it's always cool to see performance benchmarking.

Out of curiosity: are those benchmarks taken with or without this last fix? Making connections is a lot slower using make_unique since they will be allocated on the heap.

**Closed** 2015-05-02 10:19 UTC
Labels: bug
